version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 4001:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  web:
    build: .
    command: python index.py
    volumes:
      - .:/code
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - .env
