"""empty message

Revision ID: 00414016e560
Revises: ac227abf5950
Create Date: 2020-11-02 22:38:11.718047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00414016e560'
down_revision = 'ac227abf5950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_set_veokit_installation_id'), 'tasks_set', ['veokit_installation_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['tasks_set.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_index(op.f('ix_tasks_set_veokit_installation_id'), table_name='tasks_set')
    op.drop_table('tasks_set')
    # ### end Alembic commands ###
