"""empty message

Revision ID: 023a7ce73a6d
Revises: 0f9fdcc50d92
Create Date: 2020-08-27 14:47:19.499770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023a7ce73a6d'
down_revision = '0f9fdcc50d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'index')
    # ### end Alembic commands ###
