"""empty message

Revision ID: 0dbb350d15bf
Revises: 60765e5bcfe0
Create Date: 2020-08-28 22:31:40.109380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbb350d15bf'
down_revision = '60765e5bcfe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lead', 'status', ['status_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead', type_='foreignkey')
    op.drop_column('lead', 'status_id')
    # ### end Alembic commands ###
