"""empty message

Revision ID: 1128c07ec7b7
Revises: 4d54ae6c1a67
Create Date: 2020-10-21 20:56:31.961767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1128c07ec7b7'
down_revision = '4d54ae6c1a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installation_integration_settings', sa.Column('veokit_integration_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_installation_integration_settings_veokit_integration_id'), 'installation_integration_settings', ['veokit_integration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installation_integration_settings_veokit_integration_id'), table_name='installation_integration_settings')
    op.drop_column('installation_integration_settings', 'veokit_integration_id')
    # ### end Alembic commands ###
