"""empty message

Revision ID: 270d0de2288b
Revises: ab21f41566b8
Create Date: 2020-10-15 15:56:10.647682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270d0de2288b'
down_revision = 'ab21f41566b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation_card_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_enabled', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.Enum('usd', 'cad', 'eur', 'aed', 'afn', 'all', 'amd', 'ars', 'aud', 'azn', 'bam', 'bdt', 'bgn', 'bhd', 'bif', 'bnd', 'bob', 'brl', 'bwp', 'byn', 'bzd', 'cdf', 'chf', 'clp', 'cny', 'cop', 'crc', 'cve', 'czk', 'djf', 'dkk', 'dop', 'dzd', 'eek', 'egp', 'ern', 'etb', 'gbp', 'gel', 'ghs', 'gnf', 'gtq', 'hkd', 'hnl', 'hrk', 'huf', 'idr', 'ils', 'inr', 'iqd', 'irr', 'isk', 'jmd', 'jod', 'jpy', 'kes', 'khr', 'kmf', 'krw', 'kwd', 'kzt', 'lbp', 'lkr', 'ltl', 'lvl', 'lyd', 'mad', 'mdl', 'mga', 'mkd', 'mmk', 'mop', 'mur', 'mxn', 'myr', 'mzn', 'nad', 'ngn', 'nio', 'nok', 'npr', 'nzd', 'omr', 'pab', 'pen', 'php', 'pkr', 'pln', 'pyg', 'qar', 'ron', 'rsd', 'rub', 'rwf', 'sar', 'sdg', 'sek', 'sgd', 'sos', 'syp', 'thb', 'tnd', 'top', 'tru', 'ttd', 'twd', 'tzs', 'uah', 'ugx', 'uyu', 'uzs', 'vef', 'vnd', 'xaf', 'xof', 'yer', 'zar', 'zmk', 'zwl', name='cardcurrencies'), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_card_settings_veokit_installation_id'), 'installation_card_settings', ['veokit_installation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installation_card_settings_veokit_installation_id'), table_name='installation_card_settings')
    op.drop_table('installation_card_settings')
    # ### end Alembic commands ###
