"""empty message

Revision ID: 2db6b9a1fd5d
Revises: 5de2c8bcf0bd
Create Date: 2020-09-05 20:04:14.534621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '2db6b9a1fd5d'
down_revision = '5de2c8bcf0bd'
branch_labels = None
depends_on = None


def upgrade():
    status_color = postgresql.ENUM('red', 'pink', 'purple', 'blue', 'green', 'orange', name='statuscolor')
    status_color.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('color', sa.Enum('red', 'pink', 'purple', 'blue', 'green', 'orange', name='statuscolor')))
    # ### end Alembic commands ###

    op.execute("UPDATE status SET color = 'blue'")
    op.alter_column('status', 'color', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'color')
    # ### end Alembic commands ###
