"""empty message

Revision ID: 30ebb909e393
Revises: 023a7ce73a6d
Create Date: 2020-08-28 07:27:28.818917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ebb909e393'
down_revision = '023a7ce73a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('value_type', sa.Enum('string', 'number', 'boolean', 'select', name='fieldtype'), nullable=False),
    sa.Column('as_title', sa.Boolean(), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=True),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('max', sa.Integer(), nullable=True),
    sa.Column('veokit_system_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_veokit_system_id'), 'field', ['veokit_system_id'], unique=False)
    op.create_table('field_select_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_select_option_field_id'), 'field_select_option', ['field_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_select_option_field_id'), table_name='field_select_option')
    op.drop_table('field_select_option')
    op.drop_index(op.f('ix_field_veokit_system_id'), table_name='field')
    op.drop_table('field')
    # ### end Alembic commands ###
