"""empty message

Revision ID: 421811e6694a
Revises: 30ebb909e393
Create Date: 2020-08-28 12:01:38.882821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421811e6694a'
down_revision = '30ebb909e393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_veokit_system_id'), 'lead', ['veokit_system_id'], unique=False)
    op.create_table('lead_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_tag')
    op.drop_table('lead_field')
    op.drop_index(op.f('ix_lead_veokit_system_id'), table_name='lead')
    op.drop_table('lead')
    # ### end Alembic commands ###
