"""empty message

Revision ID: 456215eb899a
Revises: 8d6947154265
Create Date: 2020-11-05 00:17:51.997333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456215eb899a'
down_revision = '8d6947154265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'name',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    # ### end Alembic commands ###
