"""empty message

Revision ID: 4d54ae6c1a67
Revises: 3a96d0ed82f4
Create Date: 2020-10-21 20:55:17.316832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d54ae6c1a67'
down_revision = '3a96d0ed82f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation_integration_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.Column('integration', sa.Enum('tilda', name='installationintegration'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_integration_settings_veokit_installation_id'), 'installation_integration_settings', ['veokit_installation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installation_integration_settings_veokit_installation_id'), table_name='installation_integration_settings')
    op.drop_table('installation_integration_settings')
    # ### end Alembic commands ###
