"""empty message

Revision ID: 4e7314b31207
Revises: 7961edc228d1
Create Date: 2020-09-10 18:32:16.998711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7314b31207'
down_revision = '7961edc228d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('utm_campaign', sa.String(length=500), nullable=True))
    op.add_column('lead', sa.Column('utm_content', sa.String(length=500), nullable=True))
    op.add_column('lead', sa.Column('utm_medium', sa.String(length=500), nullable=True))
    op.add_column('lead', sa.Column('utm_source', sa.String(length=500), nullable=True))
    op.add_column('lead', sa.Column('utm_term', sa.String(length=500), nullable=True))
    op.drop_constraint('lead_field_lead_id_fkey', 'lead_field', type_='foreignkey')
    op.drop_constraint('lead_field_field_id_fkey', 'lead_field', type_='foreignkey')
    op.create_foreign_key(None, 'lead_field', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_field', 'field', ['field_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('lead_tag_tag_id_fkey', 'lead_tag', type_='foreignkey')
    op.drop_constraint('lead_tag_lead_id_fkey', 'lead_tag', type_='foreignkey')
    op.create_foreign_key(None, 'lead_tag', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_tag', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_tag', type_='foreignkey')
    op.drop_constraint(None, 'lead_tag', type_='foreignkey')
    op.create_foreign_key('lead_tag_lead_id_fkey', 'lead_tag', 'lead', ['lead_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('lead_tag_tag_id_fkey', 'lead_tag', 'tag', ['tag_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'lead_field', type_='foreignkey')
    op.drop_constraint(None, 'lead_field', type_='foreignkey')
    op.create_foreign_key('lead_field_field_id_fkey', 'lead_field', 'field', ['field_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('lead_field_lead_id_fkey', 'lead_field', 'lead', ['lead_id'], ['id'], ondelete='SET NULL')
    op.drop_column('lead', 'utm_term')
    op.drop_column('lead', 'utm_source')
    op.drop_column('lead', 'utm_medium')
    op.drop_column('lead', 'utm_content')
    op.drop_column('lead', 'utm_campaign')
    # ### end Alembic commands ###
