"""empty message

Revision ID: 575509f11860
Revises: 7af0105b05b1
Create Date: 2020-10-15 22:16:37.084076

"""
from alembic import op
import sqlalchemy as sa
from flaskr.models.lead import Lead


# revision identifiers, used by Alembic.
revision = '575509f11860'
down_revision = '7af0105b05b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('uid', sa.String(length=10), nullable=True, server_default='noUid'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'uid')
    # ### end Alembic commands ###
