"""empty message

Revision ID: 5de2c8bcf0bd
Revises: eae309e26604
Create Date: 2020-08-29 09:29:52.729418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de2c8bcf0bd'
down_revision = 'eae309e26604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_field', sa.Column('field_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lead_field', 'field', ['field_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_field', type_='foreignkey')
    op.drop_column('lead_field', 'field_id')
    # ### end Alembic commands ###
