"""empty message

Revision ID: 622accf3f06c
Revises: cce61e92d6ed
Create Date: 2020-09-19 15:51:01.137416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622accf3f06c'
down_revision = 'cce61e92d6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'lead', 'status', ['status_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'lead_field', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_field', 'field', ['field_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_tag', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_tag', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_tag', type_='foreignkey')
    op.drop_constraint(None, 'lead_tag', type_='foreignkey')
    op.drop_constraint(None, 'lead_field', type_='foreignkey')
    op.drop_constraint(None, 'lead_field', type_='foreignkey')
    op.drop_constraint(None, 'lead', type_='foreignkey')
    # ### end Alembic commands ###
