"""empty message

Revision ID: 70081f4add0a
Revises: d5ca56cdcc47
Create Date: 2020-11-04 19:00:57.968691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70081f4add0a'
down_revision = 'd5ca56cdcc47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_tasks_set_veokit_installation_id', table_name='tasks_set')
    op.add_column('lead_completed_task', sa.Column('subtask_id', sa.Integer(), nullable=True))
    op.alter_column('lead_completed_task', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'lead_completed_task', 'subtask', ['subtask_id'], ['id'], ondelete='CASCADE')
    op.add_column('task', sa.Column('veokit_installation_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_task_veokit_installation_id'), 'task', ['veokit_installation_id'], unique=False)
    op.drop_constraint('task_set_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'set_id')
    op.drop_table('tasks_set')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('set_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('task_set_id_fkey', 'task', 'tasks_set', ['set_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_task_veokit_installation_id'), table_name='task')
    op.drop_column('task', 'veokit_installation_id')
    op.drop_constraint(None, 'lead_completed_task', type_='foreignkey')
    op.alter_column('lead_completed_task', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('lead_completed_task', 'subtask_id')
    op.create_table('tasks_set',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('veokit_installation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tasks_set_pkey')
    )
    op.create_index('ix_tasks_set_veokit_installation_id', 'tasks_set', ['veokit_installation_id'], unique=False)
    op.drop_table('subtask')
    # ### end Alembic commands ###
