"""empty message

Revision ID: 7961edc228d1
Revises: 87fccdcf4b83
Create Date: 2020-09-06 20:40:32.797216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7961edc228d1'
down_revision = '87fccdcf4b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field', sa.Column('index', sa.Integer(), nullable=True))
    op.alter_column('field', 'veokit_installation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lead', 'veokit_installation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('status', 'veokit_installation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tag', 'veokit_installation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('token', 'veokit_installation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'veokit_installation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tag', 'veokit_installation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('status', 'veokit_installation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lead', 'veokit_installation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('field', 'veokit_installation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('field', 'index')
    # ### end Alembic commands ###
