"""empty message

Revision ID: 7af0105b05b1
Revises: 270d0de2288b
Create Date: 2020-10-15 18:34:37.923849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af0105b05b1'
down_revision = '270d0de2288b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'amount')
    # ### end Alembic commands ###
