"""empty message

Revision ID: 7f48ce4f42ee
Revises: 
Create Date: 2020-10-25 16:24:16.236666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f48ce4f42ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('value_type', sa.Enum('string', 'long_string', 'number', 'boolean', 'date', name='fieldtype'), server_default='string', nullable=False),
    sa.Column('board_visibility', sa.Enum('none', 'title', 'subtitle', name='fieldboardvisibility'), server_default='none', nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_veokit_installation_id'), 'field', ['veokit_installation_id'], unique=False)
    op.create_table('installation_card_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_enabled', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.Enum('usd', 'cad', 'eur', 'aed', 'afn', 'all', 'amd', 'ars', 'aud', 'azn', 'bam', 'bdt', 'bgn', 'bhd', 'bif', 'bnd', 'bob', 'brl', 'bwp', 'byn', 'bzd', 'cdf', 'chf', 'clp', 'cny', 'cop', 'crc', 'cve', 'czk', 'djf', 'dkk', 'dop', 'dzd', 'eek', 'egp', 'ern', 'etb', 'gbp', 'gel', 'ghs', 'gnf', 'gtq', 'hkd', 'hnl', 'hrk', 'huf', 'idr', 'ils', 'inr', 'iqd', 'irr', 'isk', 'jmd', 'jod', 'jpy', 'kes', 'khr', 'kmf', 'krw', 'kwd', 'kzt', 'lbp', 'lkr', 'ltl', 'lvl', 'lyd', 'mad', 'mdl', 'mga', 'mkd', 'mmk', 'mop', 'mur', 'mxn', 'myr', 'mzn', 'nad', 'ngn', 'nio', 'nok', 'npr', 'nzd', 'omr', 'pab', 'pen', 'php', 'pkr', 'pln', 'pyg', 'qar', 'ron', 'rsd', 'rub', 'rwf', 'sar', 'sdg', 'sek', 'sgd', 'sos', 'syp', 'thb', 'tnd', 'top', 'tru', 'ttd', 'twd', 'tzs', 'uah', 'ugx', 'uyu', 'uzs', 'vef', 'vnd', 'xaf', 'xof', 'yer', 'zar', 'zmk', 'zwl', name='cardcurrencies'), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_card_settings_veokit_installation_id'), 'installation_card_settings', ['veokit_installation_id'], unique=False)
    op.create_table('installation_extension_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.Column('veokit_extension_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_extension_settings_veokit_extension_id'), 'installation_extension_settings', ['veokit_extension_id'], unique=False)
    op.create_index(op.f('ix_installation_extension_settings_veokit_installation_id'), 'installation_extension_settings', ['veokit_installation_id'], unique=False)
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.Enum('red', 'pink', 'purple', 'blue', 'green', 'orange', name='statuscolor'), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_veokit_installation_id'), 'status', ['veokit_installation_id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_veokit_installation_id'), 'tag', ['veokit_installation_id'], unique=False)
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=300), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=8), nullable=True),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.Column('veokit_user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('utm_source', sa.String(length=500), nullable=True),
    sa.Column('utm_medium', sa.String(length=500), nullable=True),
    sa.Column('utm_campaign', sa.String(length=500), nullable=True),
    sa.Column('utm_term', sa.String(length=500), nullable=True),
    sa.Column('utm_content', sa.String(length=500), nullable=True),
    # sa.ForeignKeyConstraint(['status_id'], ['status.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_veokit_installation_id'), 'lead', ['veokit_installation_id'], unique=False)
    op.create_index(op.f('ix_lead_veokit_user_id'), 'lead', ['veokit_user_id'], unique=False)
    op.create_table('lead_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('create_lead', 'update_lead', 'update_lead_status', 'archive_lead', 'restore_lead', name='leadactiontype'), nullable=False),
    sa.Column('old_status_id', sa.Integer(), nullable=True),
    sa.Column('new_status_id', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('veokit_user_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['new_status_id'], ['status.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['old_status_id'], ['status.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_action_veokit_user_id'), 'lead_action', ['veokit_user_id'], unique=False)
    op.create_table('lead_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['field_id'], ['field.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_tag')
    op.drop_table('lead_field')
    op.drop_index(op.f('ix_lead_action_veokit_user_id'), table_name='lead_action')
    op.drop_table('lead_action')
    op.drop_index(op.f('ix_lead_veokit_user_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_veokit_installation_id'), table_name='lead')
    op.drop_table('lead')
    op.drop_table('token')
    op.drop_index(op.f('ix_tag_veokit_installation_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_status_veokit_installation_id'), table_name='status')
    op.drop_table('status')
    op.drop_index(op.f('ix_installation_extension_settings_veokit_installation_id'), table_name='installation_extension_settings')
    op.drop_index(op.f('ix_installation_extension_settings_veokit_extension_id'), table_name='installation_extension_settings')
    op.drop_table('installation_extension_settings')
    op.drop_index(op.f('ix_installation_card_settings_veokit_installation_id'), table_name='installation_card_settings')
    op.drop_table('installation_card_settings')
    op.drop_index(op.f('ix_field_veokit_installation_id'), table_name='field')
    op.drop_table('field')
    # ### end Alembic commands ###
