"""empty message

Revision ID: 86d2af4bab3e
Revises: ef9736d548a6
Create Date: 2020-10-24 00:16:01.293917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86d2af4bab3e'
down_revision = 'ef9736d548a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation_extension_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.Column('extension', sa.String(length=32), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_extension_settings_veokit_installation_id'), 'installation_extension_settings', ['veokit_installation_id'], unique=False)
    op.drop_index('ix_installation_integration_settings_veokit_installation_id', table_name='installation_integration_settings')
    op.drop_table('installation_integration_settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation_integration_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('veokit_installation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('integration', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='installation_integration_settings_pkey')
    )
    op.create_index('ix_installation_integration_settings_veokit_installation_id', 'installation_integration_settings', ['veokit_installation_id'], unique=False)
    op.drop_index(op.f('ix_installation_extension_settings_veokit_installation_id'), table_name='installation_extension_settings')
    op.drop_table('installation_extension_settings')
    # ### end Alembic commands ###
