"""empty message

Revision ID: 8866957e4add
Revises: cf21eb9afcd5
Create Date: 2020-10-22 17:19:55.853058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8866957e4add'
down_revision = 'cf21eb9afcd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installation_integration_settings', sa.Column('token', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installation_integration_settings', 'token')
    # ### end Alembic commands ###
