"""empty message

Revision ID: 8a9d0e0de544
Revises: e62cdefc4bb1
Create Date: 2020-08-28 22:48:27.805666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a9d0e0de544'
down_revision = 'e62cdefc4bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('archived', sa.Boolean(), nullable=False))
    op.drop_column('lead', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('lead', 'archived')
    # ### end Alembic commands ###
