"""empty message

Revision ID: 8ab7fe6bb033
Revises: 8bdd3eb746b5
Create Date: 2020-11-09 20:32:45.746996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab7fe6bb033'
down_revision = '8bdd3eb746b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'lead', 'status', ['status_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'lead_action', 'status', ['new_status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_action', 'status', ['old_status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_action', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_action', 'task', ['completed_task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_completed_task', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_completed_task', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_field', 'field', ['field_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_field', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_tag', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_tag', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'task', ['parent_task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'lead_tag', type_='foreignkey')
    op.drop_constraint(None, 'lead_tag', type_='foreignkey')
    op.drop_constraint(None, 'lead_field', type_='foreignkey')
    op.drop_constraint(None, 'lead_field', type_='foreignkey')
    op.drop_constraint(None, 'lead_completed_task', type_='foreignkey')
    op.drop_constraint(None, 'lead_completed_task', type_='foreignkey')
    op.drop_constraint(None, 'lead_action', type_='foreignkey')
    op.drop_constraint(None, 'lead_action', type_='foreignkey')
    op.drop_constraint(None, 'lead_action', type_='foreignkey')
    op.drop_constraint(None, 'lead_action', type_='foreignkey')
    op.drop_constraint(None, 'lead', type_='foreignkey')
    # ### end Alembic commands ###
