"""empty message

Revision ID: 8d6947154265
Revises: f84017dc3c28
Create Date: 2020-11-04 22:52:26.967663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6947154265'
down_revision = 'f84017dc3c28'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TYPE leadactiontype ADD VALUE 'complete_task'")
    op.execute("ALTER TYPE leadactiontype ADD VALUE 'revert_complete_task'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_action', sa.Column('completed_task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lead_action', 'task', ['completed_task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_action', type_='foreignkey')
    op.drop_column('lead_action', 'completed_task_id')
    # ### end Alembic commands ###
