"""empty message

Revision ID: a66e6480f3cf
Revises: 8ab7fe6bb033
Create Date: 2020-12-04 21:49:45.816911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66e6480f3cf'
down_revision = '8ab7fe6bb033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('comment', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'comment')
    # ### end Alembic commands ###
