"""empty message

Revision ID: ac227abf5950
Revises: 7f48ce4f42ee
Create Date: 2020-10-25 16:36:06.679502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac227abf5950'
down_revision = '7f48ce4f42ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'lead', 'status', ['status_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'lead_action', 'status', ['new_status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_action', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_action', 'status', ['old_status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_field', 'field', ['field_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_field', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_tag', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_tag', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_tag', type_='foreignkey')
    op.drop_constraint(None, 'lead_tag', type_='foreignkey')
    op.drop_constraint(None, 'lead_field', type_='foreignkey')
    op.drop_constraint(None, 'lead_field', type_='foreignkey')
    op.drop_constraint(None, 'lead_action', type_='foreignkey')
    op.drop_constraint(None, 'lead_action', type_='foreignkey')
    op.drop_constraint(None, 'lead_action', type_='foreignkey')
    op.drop_constraint(None, 'lead', type_='foreignkey')
    # ### end Alembic commands ###
