"""empty message

Revision ID: b18428ad50df
Revises: 622accf3f06c
Create Date: 2020-09-19 17:32:19.606624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18428ad50df'
down_revision = '622accf3f06c'
branch_labels = None
depends_on = None


def upgrade():
    # Update fieldtype enum
    op.execute("ALTER TYPE fieldtype ADD VALUE 'long_string'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('field', 'as_title',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('field', 'index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('field', 'primary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('status', 'index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('token', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('token', 'token',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'token',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('token', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('status', 'index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('field', 'primary',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('field', 'index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('field', 'as_title',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
