"""empty message

Revision ID: b4f80ff8bfe1
Revises: 29aff126e34c
Create Date: 2020-10-17 10:31:02.029610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f80ff8bfe1'
down_revision = '29aff126e34c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('veokit_user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_action_veokit_user_id'), 'action', ['veokit_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_veokit_user_id'), table_name='action')
    op.drop_column('action', 'veokit_user_id')
    # ### end Alembic commands ###
