"""empty message

Revision ID: cce61e92d6ed
Revises: 
Create Date: 2020-09-19 15:50:26.356492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce61e92d6ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('value_type', sa.Enum('string', 'number', 'boolean', 'select', name='fieldtype'), nullable=False),
    sa.Column('as_title', sa.Boolean(), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=True),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('max', sa.Integer(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_veokit_installation_id'), 'field', ['veokit_installation_id'], unique=False)
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.Enum('red', 'pink', 'purple', 'blue', 'green', 'orange', name='statuscolor'), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_veokit_installation_id'), 'status', ['veokit_installation_id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_veokit_installation_id'), 'tag', ['veokit_installation_id'], unique=False)
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=300), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('veokit_installation_id', sa.Integer(), nullable=False),
    sa.Column('veokit_user_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('utm_source', sa.String(length=500), nullable=True),
    sa.Column('utm_medium', sa.String(length=500), nullable=True),
    sa.Column('utm_campaign', sa.String(length=500), nullable=True),
    sa.Column('utm_term', sa.String(length=500), nullable=True),
    sa.Column('utm_content', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_veokit_installation_id'), 'lead', ['veokit_installation_id'], unique=False)
    op.create_index(op.f('ix_lead_veokit_user_id'), 'lead', ['veokit_user_id'], unique=False)
    op.create_table('lead_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_tag')
    op.drop_table('lead_field')
    op.drop_index(op.f('ix_lead_veokit_user_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_veokit_installation_id'), table_name='lead')
    op.drop_table('lead')
    op.drop_table('token')
    op.drop_index(op.f('ix_tag_veokit_installation_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_status_veokit_installation_id'), table_name='status')
    op.drop_table('status')
    op.drop_index(op.f('ix_field_veokit_installation_id'), table_name='field')
    op.drop_table('field')
    # ### end Alembic commands ###
