"""empty message

Revision ID: cf21eb9afcd5
Revises: 1128c07ec7b7
Create Date: 2020-10-21 21:29:49.323355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf21eb9afcd5'
down_revision = '1128c07ec7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_installation_integration_settings_veokit_integration_id', table_name='installation_integration_settings')
    op.drop_column('installation_integration_settings', 'veokit_integration_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installation_integration_settings', sa.Column('veokit_integration_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_installation_integration_settings_veokit_integration_id', 'installation_integration_settings', ['veokit_integration_id'], unique=False)
    # ### end Alembic commands ###
