"""empty message

Revision ID: cfb890285269
Revises: 78ad53eb5e23
Create Date: 2021-01-11 02:14:52.310135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb890285269'
down_revision = '78ad53eb5e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'lead', 'status', ['status_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'lead_action', 'status', ['new_status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_action', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_action', 'task', ['completed_task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_action', 'status', ['old_status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_completed_task', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_completed_task', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_field', 'field', ['field_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_field', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_tag', 'lead', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_tag', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'task', ['parent_task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'lead_tag', type_='foreignkey')
    op.drop_constraint(None, 'lead_tag', type_='foreignkey')
    op.drop_constraint(None, 'lead_field', type_='foreignkey')
    op.drop_constraint(None, 'lead_field', type_='foreignkey')
    op.drop_constraint(None, 'lead_completed_task', type_='foreignkey')
    op.drop_constraint(None, 'lead_completed_task', type_='foreignkey')
    op.drop_constraint(None, 'lead_action', type_='foreignkey')
    op.drop_constraint(None, 'lead_action', type_='foreignkey')
    op.drop_constraint(None, 'lead_action', type_='foreignkey')
    op.drop_constraint(None, 'lead_action', type_='foreignkey')
    op.drop_constraint(None, 'lead', type_='foreignkey')
    # ### end Alembic commands ###
