"""empty message

Revision ID: e62cdefc4bb1
Revises: 0dbb350d15bf
Create Date: 2020-08-28 22:45:13.184117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62cdefc4bb1'
down_revision = '0dbb350d15bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('tags', sa.ARRAY(sa.String())))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'tags')
    # ### end Alembic commands ###
