"""empty message

Revision ID: eae309e26604
Revises: 8a9d0e0de544
Create Date: 2020-08-28 23:27:40.025804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae309e26604'
down_revision = '8a9d0e0de544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('veokit_system_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_veokit_system_id'), 'tag', ['veokit_system_id'], unique=False)
    op.add_column('lead_tag', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lead_tag', 'tag', ['tag_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_tag', type_='foreignkey')
    op.drop_column('lead_tag', 'tag_id')
    op.drop_index(op.f('ix_tag_veokit_system_id'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
