"""empty message

Revision ID: ef9736d548a6
Revises: 0bf55fa82fa2
Create Date: 2020-10-22 20:39:37.417403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9736d548a6'
down_revision = '0bf55fa82fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installation_integration_settings', sa.Column('integration', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installation_integration_settings', 'integration')
    # ### end Alembic commands ###
