"""empty message

Revision ID: f84017dc3c28
Revises: 70081f4add0a
Create Date: 2020-11-04 21:34:02.748537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84017dc3c28'
down_revision = '70081f4add0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lead_completed_task_subtask_id_fkey', 'lead_completed_task', type_='foreignkey')
    op.drop_column('lead_completed_task', 'subtask_id')
    op.add_column('task', sa.Column('parent_task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'task', ['parent_task_id'], ['id'], ondelete='SET NULL')
    op.drop_table('subtask')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'parent_task_id')
    op.add_column('lead_completed_task', sa.Column('subtask_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('lead_completed_task_subtask_id_fkey', 'lead_completed_task', 'subtask', ['subtask_id'], ['id'], ondelete='CASCADE')
    op.create_table('subtask',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='subtask_task_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='subtask_pkey')
    )
    # ### end Alembic commands ###
