"""empty message

Revision ID: fbb325893a43
Revises: 4e7314b31207
Create Date: 2020-09-11 12:13:04.647900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb325893a43'
down_revision = '4e7314b31207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_field_select_option_field_id', table_name='field_select_option')
    op.drop_table('field_select_option')
    op.add_column('lead', sa.Column('veokit_user_id', sa.Integer()))
    op.create_index(op.f('ix_lead_veokit_user_id'), 'lead', ['veokit_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_veokit_user_id'), table_name='lead')
    op.drop_column('lead', 'veokit_user_id')
    op.create_table('field_select_option',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('label', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('field_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='field_select_option_pkey')
    )
    op.create_index('ix_field_select_option_field_id', 'field_select_option', ['field_id'], unique=False)
    # ### end Alembic commands ###
